package GUI;

import java.util.Arrays;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hsedi
 */
public class Login extends javax.swing.JFrame {
    
   private EmployeeEditor employeEditor = new EmployeeEditor();
   private CustomerEditor customerEditor = new CustomerEditor();

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextUserName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtnEmployeeLogin = new javax.swing.JButton();
        jbtnAdminLogin = new javax.swing.JButton();
        jPasswordUserPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("High Street Bank");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Vivaldi", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("High Street Bank");

        jLabel2.setText("User Name");

        jLabel3.setText("User Password");

        jbtnEmployeeLogin.setBackground(new java.awt.Color(102, 102, 255));
        jbtnEmployeeLogin.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jbtnEmployeeLogin.setText("Employee Login");
        jbtnEmployeeLogin.setToolTipText("Click here to login as employee.");
        jbtnEmployeeLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEmployeeLoginActionPerformed(evt);
            }
        });

        jbtnAdminLogin.setBackground(new java.awt.Color(102, 102, 255));
        jbtnAdminLogin.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jbtnAdminLogin.setText("Admin Login");
        jbtnAdminLogin.setToolTipText("Click here if you ara a ADMIN");
        jbtnAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAdminLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jPasswordUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnEmployeeLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnAdminLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtnAdminLogin, jbtnEmployeeLogin});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnEmployeeLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnEmployeeLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEmployeeLoginActionPerformed
        // TODO add your handling code here:
        char[] userPassword = jPasswordUserPassword.getPassword();
        String userName = jTextUserName.getText();
        
        if(!(userName.equals(""))){ //check userName field is empty returns true if it is not empty
            if (findUser(userName)&&(paswordValidation(userPassword,userName, "employee"))) {                   
               customerEditor.setVisible(true);
               }
            else
                JOptionPane.showMessageDialog(null, "Wrong Credentials", "ERROR", JOptionPane.ERROR_MESSAGE);
        }else {
             JOptionPane.showMessageDialog(null, "Some fields are empty", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jbtnEmployeeLoginActionPerformed

    private void jbtnAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAdminLoginActionPerformed
        // TODO add your handling code here:
        
        char[] userPassword = jPasswordUserPassword.getPassword();
        String userName = jTextUserName.getText();
        
        if(!(userName.equals(""))){ //check userName field is empty returns true if it is not empty
            if (findAdmin(userName)&&(paswordValidation(userPassword,userName,"admin"))) {                   
               employeEditor.setVisible(true);
               }
            else
                JOptionPane.showMessageDialog(null, "Wrong Credentials", "ERROR", JOptionPane.ERROR_MESSAGE);
        }else {
             JOptionPane.showMessageDialog(null, "Some fields are empty", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jbtnAdminLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordUserPassword;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextUserName;
    private javax.swing.JButton jbtnAdminLogin;
    private javax.swing.JButton jbtnEmployeeLogin;
    // End of variables declaration//GEN-END:variables

    private boolean paswordValidation(char[] userPassword, String userName, String user) {
       boolean result = false;
        String correctPassword ="";
        if (user.equalsIgnoreCase("admin")) {
              correctPassword = getAdminPassword(userName);
        }else
            correctPassword = getPassword(userName);
       System.out.println(correctPassword.length());
       char[] correctPasswordArray = new char[correctPassword.length()];
       
       //divide correct password to chars and add it to the array
        for (int i = 0; i < correctPasswordArray.length; i++) {
            correctPasswordArray[i] = correctPassword.charAt(i);         
        }
       
        if (userPassword.length != correctPasswordArray.length) {
            result = false;
        } else {
            result = Arrays.equals (userPassword, correctPasswordArray);
        }
        
        return result;
    }
    
    private static boolean findUser(java.lang.String userName) {
        webServices.EmployeeWebService_Service service = new webServices.EmployeeWebService_Service();
        webServices.EmployeeWebService port = service.getEmployeeWebServicePort();
        return port.findUser(userName);
    }

    private static String getPassword(java.lang.String arg0) {
        webServices.EmployeeWebService_Service service = new webServices.EmployeeWebService_Service();
        webServices.EmployeeWebService port = service.getEmployeeWebServicePort();
        return port.getPassword(arg0);
    }

    private static boolean findAdmin(java.lang.String userName) {
        com.bankservice.BankWebService_Service service = new com.bankservice.BankWebService_Service();
        com.bankservice.BankWebService port = service.getBankWebServicePort();
        return port.findAdmin(userName);
    }

    private static String getAdminPassword(java.lang.String userName) {
        com.bankservice.BankWebService_Service service = new com.bankservice.BankWebService_Service();
        com.bankservice.BankWebService port = service.getBankWebServicePort();
        return port.getAdminPassword(userName);
    }

    
}
